-- cartograph.k8sschema — a Kubernetes object CHECKED against the field schema derived from Kubernetes' own API types
-- (CART-1308; the schema is generated by tools/k8sapi.lua into cartograph.k8sapi_schema). The object is read as the
-- API server parses it: sigs.k8s.io/yaml over go-yaml v2, i.e. yamlvalue's `helm` profile (Helm uses the same library),
-- so `true` is a bool and `"true"` a string. Two findings, each at its line:
--   unknown-field  a key the kind's struct does not have — Kubernetes DROPS it silently (or a strict apply fails far
--                  from the cause); with a HINT when the key belongs one level DOWN (the classic `nindent 8` that should
--                  be 10: `containers` under the pod template instead of its spec), one level UP, or is a near spelling
--   wrong-type     a value the field cannot hold: a string for an int, a bool annotation, a map where a list goes
-- A kind the schema does not know (a custom resource) is not judged: counted.
local M = {}

local Y = require 'cartograph.yamlvalue'

local SCHEMA
function M.schema()
    if SCHEMA == nil then SCHEMA = require('cartograph.k8sapi').schema_load() or false end
    return SCHEMA or nil
end

local function strip(k) return (tostring(k):gsub('^%a+:', '')) end
local function vtype(v)
    if type(v) == 'table' then return v.o and 'map' or (v.a and 'list' or 'table') end
    if v == 'null' then return 'null' end
    return (tostring(v):match('^(%a+):') or tostring(v))
end

-- Levenshtein distance, bounded (a near spelling is within 2)
local function dist(a, b)
    if math.abs(#a - #b) > 2 then return 3 end
    local prev = {}
    for j = 0, #b do prev[j] = j end
    for i = 1, #a do
        local cur = { [0] = i }
        for j = 1, #b do
            local c = (a:sub(i, i) == b:sub(j, j)) and 0 or 1
            cur[j] = math.min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + c)
        end
        prev = cur
    end
    return prev[#b]
end
M._dist = dist

local function struct_key(ts) return ts and ts:match('^T:(.+)$') end
local function elem(ts) return ts and (ts:match('^list:(.+)$') or ts:match('^map:(.+)$')) end

-- why a key is unknown in struct `key` (whose parent struct is `parent`) -> hint | nil
local function hint(sc, key, parent, k)
    local T = sc.types[key] or {}
    for f, ts in pairs(T) do
        local sk = struct_key(ts) or struct_key(elem(ts))
        if sk and sc.types[sk] and sc.types[sk][k] then return ('belongs under `%s` (one level too shallow — an indentation?)'):format(f) end
    end
    if parent and sc.types[parent] and sc.types[parent][k] then return 'belongs one level up (one level too deep — an indentation?)' end
    local best, bd
    for f in pairs(T) do local d = dist(k, f); if d <= 2 and (not bd or d < bd) then best, bd = f, d end end
    if best then return ('did you mean `%s`?'):format(best) end
    return nil
end

local SCALAR_OK = {
    string = { str = true }, int = { number = true }, number = { number = true }, bool = { bool = true },
    quantity = { str = true, number = true }, intorstring = { str = true, number = true },
}

--- check one typed object (yamlvalue typed under the helm profile) of `kind` -> findings { { path, problem, expected,
--- got, hint } } | nil, why (the kind is not in the schema)
function M.check(kind, obj, sc)
    sc = sc or M.schema()
    if not sc then return nil, 'no field schema (regenerate: tools/k8sapi.lua)' end
    local root = sc.kinds[kind]
    if not root then return nil, 'kind ' .. tostring(kind) .. ' is not in the schema (a custom resource?)' end
    local out = {}
    local function walk(v, ts, path, parent)
        if v == 'null' or v == nil or ts == 'any' then return end
        local got = vtype(v)
        local sk = struct_key(ts)
        if sk then
            if got ~= 'map' then out[#out + 1] = { path = path, problem = 'wrong-type', expected = 'an object (' .. sk .. ')', got = got }; return end
            local T = sc.types[sk] or {}
            for _, k in ipairs(v.keys) do
                local key = strip(k)
                local p = path == '' and key or (path .. '.' .. key)
                local f = T[key]
                -- (a `$`-key is a STRATEGIC-MERGE-PATCH directive — $patch, $retainKeys, $setElementOrder/…,
                -- $deleteFromPrimitiveList/… in apimachinery's util/strategicpatch — never a field: a kustomize patch
                -- file is still judged for everything else)
                if key:sub(1, 1) == '$' then f = 'any' end
                if f then walk(v.o[k], f, p, sk)
                else out[#out + 1] = { path = p, problem = 'unknown-field', expected = sk, hint = hint(sc, sk, parent, key) } end
            end
            return
        end
        local le = ts:match('^list:(.+)$')
        if le then
            if got ~= 'list' then out[#out + 1] = { path = path, problem = 'wrong-type', expected = 'a list', got = got }; return end
            for i, x in ipairs(v.a) do walk(x, le, path .. '[' .. i .. ']', parent) end
            return
        end
        local me = ts:match('^map:(.+)$')
        if me then
            if got ~= 'map' then out[#out + 1] = { path = path, problem = 'wrong-type', expected = 'a map', got = got }; return end
            for _, k in ipairs(v.keys) do walk(v.o[k], me, path .. '.' .. strip(k), parent) end
            return
        end
        local ok = SCALAR_OK[ts]
        if ok and not ok[got] then
            local shown = type(v) == 'string' and v:gsub('^%a+:', '') or ''
            if got == 'number' and tonumber(shown) then shown = ('%.15g'):format(tonumber(shown)) end
            out[#out + 1] = { path = path, problem = 'wrong-type', expected = ts, got = got .. (shown ~= '' and (' ' .. shown) or '') }
        elseif ts == 'int' and got == 'number' and not tostring(v):match('^number:%-?%d+$') then
            out[#out + 1] = { path = path, problem = 'wrong-type', expected = 'an integer', got = v }
        end
    end
    walk(obj, 'T:' .. root, '', nil)
    return out
end

--- check every document of a YAML text -> { { doc, kind, name, path, problem, expected, got, hint, line } }, skipped
--- (documents of a kind the schema does not know). `line` is the document's line of the offending key (1-based, in the
--- text); `at(doc)` gives each document's first line in the text when the caller splits differently.
function M.check_text(text, sc)
    sc = sc or M.schema()
    local findings, skipped = {}, {}
    local KL = require('cartograph.helmprov').key_lines
    local pos, line0, di = 1, 0, 0
    local function each(chunk, firstline)
        local docs = Y.read(chunk)
        local d = docs and docs[1]
        if not d or type(d.value) ~= 'table' or not d.value.o or type(d.value.o.kind) ~= 'string' then return end
        di = di + 1
        local kind = d.value.o.kind
        local typed = Y.typed(d.raw, Y.IMPLEMENTATIONS.helm)
        local fs, why = M.check(kind, typed, sc)
        if not fs then skipped[#skipped + 1] = kind .. ': ' .. why; return end
        local lines = #fs > 0 and KL(chunk) or {}
        local name = d.value.o.metadata and d.value.o.metadata.o and d.value.o.metadata.o.name
        for _, f in ipairs(fs) do
            local l = lines[f.path]
            local p = f.path
            for _ = 1, 20 do if l or not p:find('[.%[]') then break end p = p:gsub('[.%[][^.%[]*$', ''); l = lines[p] end
            f.doc, f.kind, f.name, f.line = di, kind, name, l and (firstline + l - 1) or firstline
            findings[#findings + 1] = f
        end
    end
    for _ = 1, 100000 do
        local a, b = text:find('\n%-%-%-[^\n]*\n', pos - 1)
        if not a then break end
        local chunk = text:sub(pos, a)
        each(chunk, line0 + 1)
        line0 = line0 + select(2, chunk:gsub('\n', '')) + 1
        pos = b + 1
    end
    each(text:sub(pos), line0 + 1)
    return findings, skipped
end

--- every RENDERED object of a helmprov render checked, each finding located to the TEMPLATE line that wrote it (through
--- the render's byte spans) -> { { file = template file (chart-relative), line, rendered = name, … finding } }, skipped
function M.check_render(prov, sc)
    local P = require 'cartograph.helmprov'
    local out, skipped = {}, {}
    local names = vim.tbl_keys(prov.files or {})
    table.sort(names)
    for _, name in ipairs(names) do
        local content = prov.files[name].content or ''
        local fs, sk = M.check_text(content, sc)
        for _, x in ipairs(sk) do skipped[#skipped + 1] = x end
        if #fs > 0 then
            -- byte offset of each rendered line's first non-blank character
            local starts, b = {}, 0
            for line in (content .. '\n'):gmatch('([^\n]*)\n') do
                starts[#starts + 1] = b + #(line:match('^%s*') or '')
                b = b + #line + 1
            end
            for _, f in ipairs(fs) do
                local file, tline = P.position(prov, name, starts[f.line] or 0)
                f.rendered, f.rendered_line = name, f.line
                f.file, f.line = file, tline
                out[#out + 1] = f
            end
        end
    end
    return out, skipped
end

--- a finding as one line
function M.text(f)
    local what = f.problem == 'unknown-field' and ('unknown field `%s` (%s has no such field: Kubernetes drops it)'):format(f.path, f.expected)
        or ('`%s` is %s where %s goes'):format(f.path, tostring(f.got), tostring(f.expected))
    return ('%s/%s: %s%s'):format(f.kind or '?', tostring(f.name or '?'), what, f.hint and ('; ' .. f.hint) or '')
end

return M
