-- GENERATED by tools/counterexample.lua — NOT REVIEWED.
-- property: a helper may not outrun a local it reads (CART-0985)
-- OBSERVED: the helper must be inserted above `SALT`, which it reads, so `SALT` would not yet be defined where the helper lands
--
-- The assertion below is written from what the verb ACTUALLY DID, so reviewing it is a
-- judgement ("is that the right behaviour?") and not an authoring job. `PENDING` errors
-- until someone decides. TO PROMOTE: confirm the behaviour, delete the PENDING line,
-- give the test a name that says why the case matters, and move this file into tests/.
local ts = require 'cartograph.providers.treesitter'
local store = require 'cartograph.store'
local clones = require 'cartograph.clones'
local cx = require 'cartograph.cloneextract'

test('GENERATED (unreviewed): a helper may not outrun a local it reads (CART-0985)', function ()
    local root = vim.fn.tempname(); vim.fn.mkdir(root, 'p')
    local fd = assert(io.open(root .. '/m.lua', 'w'))
    fd:write([==[
local M = {}

M.alpha = function (x)
  local y = prep(x)
  local z = norm(y)
  local q = SALT + 1
  local w = enc(z, 'json')
  return w
end

local SALT = 7

M.beta = function (a)
  local b = prep(a)
  local c = norm(b)
  local q = SALT + 1
  local d = enc(c, 'yaml')
  return d
end

return M
]==])
    fd:close()
    store.ingest(ts.extract(root))
    local id
    for _, nd in ipairs(store.data.nodes) do
        if nd.name == 'M.alpha' or nd.name == 'alpha' then id = nd.id end
    end
    local pair = id and clones.near_of(store, id,
        { max_dist = 3, min_rows = 3, min_shared = 2 })[1]
    ok(pair, 'the two copies are a near-clone pair')
    if not pair then return end
    -- ⚠ NOT `pair and cx.plan(…)`: AN `and` IS A VALUE, NOT A CALL, so it TRUNCATES to
    -- one return and `why` arrives nil. certificate.lua carries a note saying this
    -- gotcha had already bitten three times in this arc; the first version of THIS
    -- EMITTER made it four, identically in all six generated tests — one template, one
    -- wrong premise, six instances that look like six witnesses.
    local plan, why = cx.plan(store, pair, {})
    ok(not plan, 'it refuses rather than planning')
    ok(tostring(why):find("must be inserted above", 1, true), tostring(why))
    vim.fn.delete(root, 'rf')
end)
