-- k8sapi — GENERATE lua/cartograph/k8sapi_table.lua from Kubernetes' own API types (CART-1267, CART-1296).
--
--   nvim --headless -u NONE -l tools/k8sapi.lua <kubernetes checkout> [--check]
--
-- The table is DERIVED (cartograph.k8sapi: kinds from register.go, pod-template paths, soft-edge references and their
-- target kinds, cluster scope from +genclient:nonNamespaced) and shipped so k8s.lua works without a checkout; this
-- tool is the only writer. --check re-derives and compares byte for byte: a newer Kubernetes that moved a path or
-- added a reference is DRIFT, named, and the exit status is 1.
local REPO = vim.fn.fnamemodify(debug.getinfo(1, 'S').source:sub(2), ':p:h:h')
package.path = REPO .. '/lua/?.lua;' .. REPO .. '/lua/?/init.lua;' .. package.path
local K = require 'cartograph.k8sapi'
local src = arg[1]
if not src then io.stderr:write('usage: k8sapi.lua <kubernetes checkout> [--check]\n'); os.exit(2) end
local check = arg[2] == '--check'
local api = vim.fn.fnamemodify(src, ':p'):gsub('/$', '') .. '/staging/src/k8s.io/api'
local S, why = K.read(api)
if not S then io.stderr:write('k8sapi: ' .. tostring(why) .. '\n'); os.exit(1) end
local r = vim.system({ 'git', '-C', src, 'rev-parse', '--short=12', 'HEAD' }, { text = true }):wait()
local stamp = 'kubernetes ' .. (r.code == 0 and vim.trim(r.stdout) or 'unknown')
local D = K.derive(S)
local header = '-- GENERATED by tools/k8sapi.lua from Kubernetes\' own API types (' .. stamp .. ') — do not edit by hand;\n'
    .. '-- regenerate: nvim --headless -u NONE -l tools/k8sapi.lua <kubernetes checkout>   (--check: drift)'
local text = K.serialize(K.table(S, D, stamp), header)
local out = REPO .. '/lua/cartograph/k8sapi_table.lua'
local nk, nc = 0, 0
for k in pairs(S.kinds) do nk = nk + 1; if S.cluster[k] then nc = nc + 1 end end
local np = 0 for _ in pairs(D.pod) do np = np + 1 end
local line = ('%s: %d kinds (%d cluster-scoped), %d pod-template kinds, %d soft-edge references'):format(stamp, nk, nc, np, #D.refs)
if check then
    local fd = io.open(out, 'rb'); local cur = fd and fd:read('a'); if fd then fd:close() end
    -- (the stamp line differs between checkouts; drift is the BODY)
    local function body(t) return (t or ''):gsub('^.-\nreturn {\n    stamp = [^\n]*\n', '') end
    if body(cur) == body(text) then io.write('k8sapi: no drift — ', line, '\n'); os.exit(0) end
    io.write('k8sapi: DRIFT against the shipped table — ', line, '\n'); os.exit(1)
end
local fd = assert(io.open(out, 'wb')); fd:write(text); fd:close()
io.write('k8sapi: wrote ', out, ' — ', line, '\n')
